import requests
import json
import os
import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

METABASE_URL = os.getenv('METABASE_URL', 'http://shopzada_metabase:3000')
METABASE_EMAIL = os.getenv('METABASE_EMAIL', 'admin@admin.com')
METABASE_PASSWORD = os.getenv('METABASE_PASSWORD', 'admin3')

def login_to_metabase():
    response = requests.post(
        f'{METABASE_URL}/api/session',
        json={'username': METABASE_EMAIL, 'password': METABASE_PASSWORD}
    )
    response.raise_for_status()
    return response.json()['id']

def get_database_id(session_token):
    headers = {'X-Metabase-Session': session_token}
    response = requests.get(f'{METABASE_URL}/api/database', headers=headers)
    response.raise_for_status()
    
    for db in response.json()['data']:
        if 'shopzada' in db['name'].lower():
            return db['id']
    raise Exception("ShopZada database not found")

def create_question(session_token, database_id, name, sql, visualization_settings=None):
    headers = {'X-Metabase-Session': session_token}
    
    payload = {
        "name": name,
        "dataset_query": {
            "type": "native",
            "native": {"query": sql},
            "database": database_id
        },
        "display": "scalar" if not visualization_settings else visualization_settings.get("display", "scalar"),
        "visualization_settings": visualization_settings or {}
    }
    
    response = requests.post(f'{METABASE_URL}/api/card', headers=headers, json=payload)
    response.raise_for_status()
    return response.json()['id']

def get_card_by_name(session_token, name):
    headers = {'X-Metabase-Session': session_token}
    response = requests.get(f'{METABASE_URL}/api/card', headers=headers)
    response.raise_for_status()
    
    cards = response.json()
    if isinstance(cards, dict) and 'data' in cards:
        cards = cards['data']
    
    for card in cards:
        if card['name'] == name:
            return card['id']
    return None

def create_staff_operations_cards():
    logging.info("Creating Staff & Operations cards...")
    
    session_token = login_to_metabase()
    logging.info("✓ Logged in to Metabase")
    
    database_id = get_database_id(session_token)
    logging.info(f"✓ Found database ID: {database_id}")
    
    questions = [
        {
            "name": "Total Staff",
            "sql": """SELECT COUNT(DISTINCT staff_key) as "Total Staff"
FROM warehouse.factorder""",
            "viz": {"display": "scalar"}
        },
        {
            "name": "Total Orders Processed by Staff",
            "sql": """SELECT COUNT(order_id) as "Total Orders Processed"
FROM warehouse.factorder""",
            "viz": {"display": "scalar"}
        },
        {
            "name": "Revenue Generated by Staff",
            "sql": """SELECT SUM(net_order_amount) as "Revenue Generated"
FROM warehouse.factorder""",
            "viz": {
                "display": "scalar",
                "column_settings": {
                    "[\"name\",\"Revenue Generated\"]": {
                        "number_style": "currency",
                        "currency": "PHP",
                        "currency_style": "symbol"
                    }
                }
            }
        },
        {
            "name": "Average Orders per Staff",
            "sql": """SELECT ROUND(
  COUNT(f.order_id)::NUMERIC / COUNT(DISTINCT f.staff_key)::NUMERIC,
  2
) as "Avg Orders per Staff"
FROM warehouse.factorder f""",
            "viz": {"display": "scalar"}
        },
        {
            "name": "Staff Performance by Volume and Revenue",
            "sql": """SELECT 
  s.name as "Staff Name",
  COUNT(f.order_id) as "Orders",
  SUM(f.net_order_amount) as "Revenue"
FROM warehouse.factorder f
JOIN warehouse.dimstaff s ON f.staff_key = s.staff_key
GROUP BY s.name
ORDER BY "Orders" DESC
LIMIT 15""",
            "viz": {
                "display": "bar",
                "column_settings": {
                    "[\"name\",\"Revenue\"]": {
                        "number_style": "currency",
                        "currency": "PHP",
                        "currency_style": "symbol"
                    }
                }
            }
        },
        {
            "name": "Performance by Job Level",
            "sql": """SELECT 
  s.job_level as "Job Level",
  COUNT(f.order_id) as "Orders",
  SUM(f.net_order_amount) as "Revenue",
  ROUND(AVG(f.net_order_amount), 2) as "AOV"
FROM warehouse.factorder f
JOIN warehouse.dimstaff s ON f.staff_key = s.staff_key
WHERE s.job_level IS NOT NULL
GROUP BY s.job_level
ORDER BY "Revenue" DESC""",
            "viz": {
                "display": "bar",
                "column_settings": {
                    "[\"name\",\"Revenue\"]": {
                        "number_style": "currency",
                        "currency": "PHP",
                        "currency_style": "symbol"
                    },
                    "[\"name\",\"AOV\"]": {
                        "number_style": "currency",
                        "currency": "PHP",
                        "currency_style": "symbol"
                    }
                }
            }
        },
        {
            "name": "Orders by Staff Location",
            "sql": """SELECT 
  s.city as "City",
  s.country as "Country",
  COUNT(f.order_id) as "Orders"
FROM warehouse.factorder f
JOIN warehouse.dimstaff s ON f.staff_key = s.staff_key
WHERE s.city IS NOT NULL
GROUP BY s.city, s.country
ORDER BY "Orders" DESC
LIMIT 15""",
            "viz": {"display": "row"}
        },
        {
            "name": "Delay Impact on Repeat Purchases",
            "sql": """WITH customer_metrics AS (
  SELECT 
    f.customer_key,
    AVG(f.delay_in_days) as avg_delay,
    COUNT(f.order_id) as order_count
  FROM warehouse.factorder f
  GROUP BY f.customer_key
)
SELECT 
  CASE 
    WHEN avg_delay < 0 THEN 'Early Delivery'
    WHEN avg_delay = 0 THEN 'On-Time'
    WHEN avg_delay BETWEEN 1 AND 3 THEN '1-3 Days Late'
    WHEN avg_delay BETWEEN 4 AND 7 THEN '4-7 Days Late'
    ELSE '8+ Days Late'
  END as "Delay Category",
  ROUND(AVG(order_count), 2) as "Avg Orders per Customer",
  COUNT(*) as "Number of Customers"
FROM customer_metrics
GROUP BY "Delay Category"
ORDER BY "Avg Orders per Customer" DESC""",
            "viz": {"display": "bar"}
        }
    ]
    
    created_cards = []
    for q in questions:
        existing_card_id = get_card_by_name(session_token, q['name'])
        if existing_card_id:
            logging.info(f"✓ Card '{q['name']}' already exists (ID: {existing_card_id})")
            created_cards.append({"name": q['name'], "id": existing_card_id, "existed": True})
        else:
            logging.info(f"Creating card: {q['name']}")
            card_id = create_question(session_token, database_id, q['name'], q['sql'], q['viz'])
            logging.info(f"✅ Created card '{q['name']}' (ID: {card_id})")
            created_cards.append({"name": q['name'], "id": card_id, "existed": False})
    
    logging.info("\n" + "="*70)
    logging.info("STAFF & OPERATIONS CARDS CREATION SUMMARY")
    logging.info("="*70)
    logging.info(f"Total Cards: {len(created_cards)}")
    logging.info(f"Newly Created: {sum(1 for c in created_cards if not c['existed'])}")
    logging.info(f"Already Existed: {sum(1 for c in created_cards if c['existed'])}")
    logging.info("="*70)
    
    return created_cards

if __name__ == "__main__":
    try:
        create_staff_operations_cards()
    except Exception as e:
        logging.error(f"❌ Failed to create Staff & Operations cards: {e}")
        exit(1)
